### PR TITLE
Add blank option for enums

### PR DESCRIPTION
**Pull request by vynmeister**
**JIRA:**
https://clever.atlassian.net/browse/SYNC-1097

Allow blank option for enums in our spec, so apps know it's a valid value.

### CODE REVIEW

**Comment by johnhuangclever** [comment]
Do we want to add to full-v1 also?

**Comment by johnhuangclever** [comment]
Also why didn't v2.0 files also get updated? 🤔

**Comment by vynmeister** [comment]
They were-- I just didn't add them in @meliaj

**Comment by meliaj** [comment]
LGTM

**Comment by johnhuangclever** [comment]
We should be updating generate.go to block out these values if we don't want to generate for pre-v2.1 files

**Pull request merged**
